# Generated by Django 3.0.4 on 2020-03-25 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10, unique=True)),
                ('articles', models.IntegerField()),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['articles'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('update_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('body', models.TextField(max_length=30000)),
                ('banner', models.ImageField(upload_to='')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
